apiVersion: v1
kind: Service
metadata:
  name: notes-app-backend-service
spec:
  selector:
    app: notes-app-backend
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
  type: LoadBalancer