apiVersion: v1
kind: Service
metadata:
  name: notes-app-frontend-service
spec:
  selector:
    app: notes-app-frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: LoadBalancer
  